services:
  zephyr:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/work          # ← repo root
    working_dir: /work
    environment:
      - LCD_OVERLAY=${LCD_OVERLAY:-}
      - LCD_DTS_OVERLAY=${LCD_DTS_OVERLAY:-}
    entrypoint: ["/work/docker/entrypoint.sh"]
    command: >
     west build
     -b xiao_ble
     firmware/app
     -d build

