services:
  zephyr:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/work          # ← repo root
    working_dir: /work
    entrypoint: ["/work/docker/entrypoint.sh"]
    command: >
     west build
     -b nrf52dk_nrf52805
     firmware/app
     -d build

